apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-ingress-rule
spec:
  ingressClassName: nginx
  rules:
   - host: todo-add.abhaysingh.shop
     http:
       paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: addtask-service
              port:
                number: 80



      
          